### PR TITLE
Adding \hat{ } functionality

### PR DESCRIPTION
**Pull request by akasher**
image

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
Actually, @akasher could you please run `flutter fromat . --fix` in your branch?

It is needed in order for the checks to pass.

**Comment by akasher** [comment]
@creativecreatorormaybenot 
I am unable to do flutter format --fix as the following error is being thrown:
image

**Comment by creativecreatorormaybenot** [comment]
@akasher this means that you are not running on `stable` 😃 You can run `dart format .` instead, but it is not guaranteed that the required check will pass because the formatting changed a bit in `beta`+.

If you checked that maintainers are allowed to edit your PR, I can quickly do it for your 🙂

**Comment by creativecreatorormaybenot** [comment]
👍🏽 I was able to format on your branch. I will open another PR after merging this one, which does some changelog stuff → if you are interested, you can check out those changes, so you could also do that next time 😃

**Comment by akasher** [comment]
> 👍🏽 I was able to format on your branch. I will open another PR after merging this one, which does some changelog stuff → if you are interested, you can check out those changes, so you could also do that next time 😃

Thanks, I will look into it the changelog stuff, yeah and you right I'm using the beta channel. I believe I will be adding functions and symbols on a rather regular basis now. By the way, this project is a really great idea, exactly what I need for my needs, and I hope for many others.

**Comment by IchordeDionysos** [comment]
@akasher Sounds awesome 😍
Really looking forward to this!

We want to build and maintain a high quality TeX package and your contributions help to achieve that goal! 💪

**Pull request merged**
