### PR TITLE
Update function_prioritization.csv

### PR DESCRIPTION
**Pull request by AlabasterAxe**
Github said that this file could be searchable and beautiful if this row had a second column.

### CODE REVIEW

**Comment by AlabasterAxe** [comment]
@cla-bot check

**Comment by AlabasterAxe** [comment]
Not sure what you want from me...

**Comment by creativecreatorormaybenot** [comment]
Hi @AlabasterAxe - thanks for the contribution and sorry for the inconvenience.

Did you enter your GitHub username [here](https://docs.google.com/forms/d/e/1FAIpQLScgn4tcwQWFjB14TQ6EnYlSR4-w6FGeCVw7_lMueLvdTWcqHA/viewform)?

**Comment by AlabasterAxe** [comment]
Yes

**Comment by AlabasterAxe** [comment]
@cla-bot check

**Comment by AlabasterAxe** [comment]
Hmm, I tried to submit again but it doesn't seem to be finding my entry.

**Comment by creativecreatorormaybenot** [comment]
@cla-bot check

**Review by creativecreatorormaybenot — APPROVED** [review]

**Comment by creativecreatorormaybenot** [comment]
@AlabasterAxe Thanks again for this improvement!

Looking forward to picking up this project again, but cannot promise anything time-wise :)

**Pull request merged**
